// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG7Fy_5PC6eK3FA5bivC1ndjaHLGZjXAU',
    appId: '1:933599181019:web:cdcbfe5a1198ba2d1074fe',
    messagingSenderId: '933599181019',
    projectId: 'flutter-vlad-1',
    authDomain: 'flutter-vlad-1.firebaseapp.com',
    storageBucket: 'flutter-vlad-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjie9pL22trnHdPLYaDKExSxhhYC0uC40',
    appId: '1:933599181019:android:44dd12d25919ee531074fe',
    messagingSenderId: '933599181019',
    projectId: 'flutter-vlad-1',
    storageBucket: 'flutter-vlad-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuikSWYQvLOuvpdGy3YXhBb_W4MMwORU',
    appId: '1:933599181019:ios:f5057357555a21b41074fe',
    messagingSenderId: '933599181019',
    projectId: 'flutter-vlad-1',
    storageBucket: 'flutter-vlad-1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuikSWYQvLOuvpdGy3YXhBb_W4MMwORU',
    appId: '1:933599181019:ios:5803da4a22aa1f8e1074fe',
    messagingSenderId: '933599181019',
    projectId: 'flutter-vlad-1',
    storageBucket: 'flutter-vlad-1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
